spring:
  datasource:
    url: jdbc:postgresql://ec2-23-21-249-224.compute-1.amazonaws.com:5432/dc36e3ssk6klpp
    username: OVERRIDE
    password: OVERRIDE
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
