spring:
  datasource:
    url: jdbc:postgresql://ec2-23-21-249-224.compute-1.amazonaws.com:5432/dc36e3ssk6klpp
    username: OVERRIDE
    password: OVERRIDE
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
  cloud:
    gateway:
      routes:
      - id: routing-service
        uri: https://openwms-routing-service.herokuapp.com/
        predicates:
        - Path=/tms
      - id: receiving
        uri: https://openwms-receiving.herokuapp.com/
        predicates:
        - Path=/orders/receiving
      - id: shipping
        uri: https://openwms-shipping.herokuapp.com/
        predicates:
        - Path=/orders/receiving
      - id: picking
        uri: https://openwms-picking.herokuapp.com/
        predicates:
        - Path=/orders/receiving

---
spring:
  profiles: DEV
  datasource:
    url: jdbc:postgresql:OPENWMS
    username: OPENWMS
    password: OPENWMS
  cloud:
    gateway:
      routes:
      - id: routing-service
        uri: http://routing-service
        predicates:
        - Path=/tms
      - id: receiving
        uri: http://receiving
        predicates:
        - Path=/orders/receiving
      - id: shipping
        uri: http://shipping
        predicates:
        - Path=/orders/receiving
      - id: picking
        uri: http://picking
        predicates:
        - Path=/orders/receiving
